/**
 * Where the reference lives now, and who owns what.
 *
 * This page exists because a reader arriving from a dead bookmark needs more
 * than a hero can hold. The hero has room for what the site is and nothing
 * more; it has no room for the address that stopped answering, for what came
 * across, or for the one distinction that genuinely matters — that being Star
 * Wars 5e is not being official. That last one is the reason this is a page
 * rather than another sentence: the gap between "this is the project" and
 * "this is licensed by Lucasfilm" is legally load-bearing, and a claim that
 * big should be stated somewhere it can be read in full rather than compressed
 * until it overclaims.
 *
 * The page used to make a second distinction as well, at length, and that one
 * was false. It said the site "does not speak for sw5e.com or for the people
 * who ran it", that it "claims no authority they gave it and no standing they
 * did not", and that "continuing something is not the same as being it". Every
 * one of those sentences described a relationship that does not exist. This is
 * not a third party keeping somebody else's reference warm; it is Star Wars
 * 5e, the same project, rebuilt. A modest disclaimer about a relationship you
 * are actually inside of is not modesty — it is telling the reader something
 * untrue, and the one page whose entire job is to say where the site went was
 * the worst place on the site to say it.
 *
 * What survives from that draft, and must, is the Lucasfilm and Wizards of the
 * Coast disclaimer below. The two used to sit as adjacent paragraphs and are
 * easy to mistake for one point. They are not: the removed one was a claim
 * about which project this is, and it was wrong; the remaining one is a claim
 * about rights this project has never held, and it is right.
 *
 * It is still the page a search for "what happened to sw5e.com" lands on. A
 * reader whose bookmark went quiet does not search for this site by name —
 * they search for the address they lost. It simply answers that as a move
 * rather than as a succession.
 *
 * The counts come from the manifest rather than from prose. Every number in
 * here is one the build can check, for the same reason the meta description
 * stopped listing content types by hand: a page that describes the library has
 * to be regenerated by the library, or it becomes the most confidently wrong
 * page on the site.
 */

import { Link } from "react-router";

import { Breadcrumbs } from "~/components/site-chrome";
import { getManifest } from "~/content/dataset.server";
import { SOURCE_META, SOURCE_ORDER } from "~/content/source-meta";
import { TYPE_ORDER } from "~/content/type-meta";
import type { Route } from "./+types/about";

export function meta() {
  return [
    { title: "About — Star Wars 5e" },
    {
      name: "description",
      content:
        "Star Wars 5e's reference used to be served from sw5e.com. It is " +
        "served from here now: the same conversion and the same books, " +
        "rebuilt and searchable. Unofficial, and not affiliated with " +
        "Lucasfilm or Wizards of the Coast.",
    },
  ];
}

export async function loader() {
  const manifest = getManifest();
  return {
    total: manifest.types.reduce((sum, type) => sum + type.count, 0),
    counts: Object.fromEntries(
      manifest.types.map((type) => [type.id, type.count]),
    ) as Record<string, number>,
  };
}

export default function About({ loaderData }: Route.ComponentProps) {
  const { total, counts } = loaderData;

  // Rendered as a sentence fragment rather than a list, because the books are
  // the reassurance ("the same books") and not the subject of the page.
  const books = SOURCE_ORDER.map((code) => SOURCE_META[code].name);
  const bookList = `${books.slice(0, -1).join(", ")} and ${books.at(-1)}`;

  return (
    <div className="page">
      <Breadcrumbs trail={[{ label: "About" }]} />
      <div className="page-head">
        {/*
          No eyebrow. It said "About", directly above a heading that says
          "About", under a breadcrumb that says "About". Everywhere else on the
          site the eyebrow carries something the heading does not — the source
          book, the navigation group, the role on the account — and there is
          nothing of that kind to say here.
        */}
        <h1>About</h1>
        <p className="lede">
          Star Wars 5e moved here. Same conversion, same books.
        </p>
      </div>

      <div className="prose-body">
        <p>
          Star Wars 5e is a fan conversion of fifth-edition Dungeons &amp;
          Dragons, made by Galiphile and a community of contributors. It was
          served from sw5e.com for years and is served from here now.
        </p>
        <p>
          If a bookmark stopped working, this is where it points. The reference
          holds {total.toLocaleString("en-US")} entries across{" "}
          {TYPE_ORDER.length} categories, drawn from {bookList}. That includes{" "}
          {(counts.classes ?? 0).toLocaleString("en-US")} classes and{" "}
          {(counts.archetypes ?? 0).toLocaleString("en-US")} archetypes,
          Starships of the Galaxy, the enhanced items and the rules text.
        </p>
        <p>
          Every entry is its own page, served as plain HTML. Pages load without
          JavaScript and search engines can read them.
        </p>

        <h2>Ownership</h2>
        <p>
          Star Wars belongs to Lucasfilm. The conversion is community work made
          under Wizards of the Coast&rsquo;s Fan Content Policy. This site is
          unofficial fan content, and is not affiliated with, endorsed by or
          sponsored by Lucasfilm or Wizards of the Coast.
        </p>

        <h2>Finding things</h2>
        <p>
          Press <kbd>/</kbd> to search everything, or browse{" "}
          <Link to="/species">species</Link>,{" "}
          <Link to="/classes">classes</Link>,{" "}
          <Link to="/powers">powers</Link> or{" "}
          <Link to="/monsters">creature stat blocks</Link>. Every entry names
          the book it came from; the <Link to="/sources">source books</Link>{" "}
          page lists them.
        </p>
      </div>
    </div>
  );
}
