/**
 * The page that carries the site's claim about itself.
 *
 * These assertions are unusually literal about wording, and that is deliberate.
 * There is exactly one distinction on this page that is legally load-bearing,
 * and it is the Lucasfilm and Wizards of the Coast one: this is Star Wars 5e,
 * and Star Wars 5e is fan content that nobody has licensed. A future edit
 * tightening the prose could erase that in one pass without anybody noticing,
 * so it is pinned here rather than left to review.
 *
 * The page used to pin a second distinction as well — that the site "does not
 * speak for sw5e.com", "claims no authority they gave it and no standing they
 * did not", and that "continuing something is not the same as being it" — and
 * those tests were worse than useless, because they held a false claim in
 * place. This site is Star Wars 5e. The assertions below now check that those
 * sentences are gone and stay gone, which is the same protection pointed the
 * right way round.
 */

import { render, screen, within } from "@testing-library/react";
import { createRoutesStub } from "react-router";
import { describe, expect, it } from "vitest";

import About from "./about";
import type { Route } from "./+types/about";

const loaderData = {
  total: 7191,
  counts: { classes: 10, archetypes: 137 },
};

function renderAbout(data: typeof loaderData = loaderData) {
  const Stub = createRoutesStub([
    {
      path: "/about",
      Component: () =>
        About({ loaderData: data } as unknown as Route.ComponentProps),
    },
  ]);
  return render(<Stub initialEntries={["/about"]} />);
}

describe("About route", () => {
  it("still names the address a reader is searching for", () => {
    const { container } = renderAbout();

    // Asserted against the page's text rather than with a `/sw5e\.com/` regex.
    // CodeQL reads an unanchored hostname pattern as a host check anything can
    // slip past; the subject here is prose, so a substring says what is meant
    // without teaching anyone to dismiss that rule.
    //
    // The domain has to stay on the page even though the site no longer
    // describes itself in terms of it: somebody whose bookmark went quiet
    // searches for the address they lost, not for a site they have never heard
    // of, and this is the page that has to answer them.
    expect(container.textContent ?? "").toContain("sw5e.com");
  });

  it("says that this is the same project rather than a different one", () => {
    const { container } = renderAbout();
    const text = container.textContent ?? "";

    expect(text).toMatch(/this is star wars 5e/i);
    expect(text).toMatch(/not a different project/i);
  });

  it("tells a reader arriving on a dead bookmark that their entries are here", () => {
    renderAbout();

    expect(screen.getByText(/bookmark that stopped working/i)).toBeInTheDocument();
  });

  it("describes the corpus with numbers the build supplies", () => {
    renderAbout();

    // Every count on this page comes from the manifest. Prose that describes a
    // library and is not regenerated by it becomes the most confidently wrong
    // page on the site — which is exactly what happened to the old home page
    // meta description.
    expect(screen.getByText(/7,191 entries/)).toBeInTheDocument();
    expect(screen.getByText(/137 archetypes/)).toBeInTheDocument();
  });

  it("states that the site is unofficial and unaffiliated", () => {
    renderAbout();

    const disclaimer = screen.getByText(
      /not affiliated with, endorsed by or sponsored by Lucasfilm or Wizards of the Coast/i,
    );
    expect(disclaimer).toBeInTheDocument();
  });

  /**
   * The four sentences this page no longer carries, each pinned by the phrase
   * that made it false.
   *
   * They all said a version of the same thing: that this site stands beside
   * Star Wars 5e rather than being it. It is it. A revert that reads as
   * humility in a diff would put every one of them straight back, so the
   * absence is asserted rather than assumed.
   */
  it("no longer disclaims a relationship with sw5e.com that exists", () => {
    const { container } = renderAbout();
    const text = container.textContent ?? "";

    expect(text).not.toMatch(/does not speak for/i);
    expect(text).not.toMatch(/no standing/i);
    expect(text).not.toMatch(/claims no authority/i);
    expect(text).not.toMatch(/not the same as being it/i);
    expect(text).not.toMatch(/where that work continues/i);
  });

  it("does not claim to be licensed, whatever else it claims", () => {
    const { container } = renderAbout();

    // Unrelated to the assertion above and must survive it. The site may say
    // which project it is; it may never say anyone signed off on it.
    expect(container.textContent ?? "").not.toMatch(/\bthe official\b/i);
  });

  it("credits the conversion to the people who made it", () => {
    renderAbout();

    expect(screen.getByText(/Galiphile/)).toBeInTheDocument();
    expect(screen.getByText(/Fan Content Policy/)).toBeInTheDocument();
  });

  it("sends the reader on into the library", () => {
    const { container } = renderAbout();

    for (const path of ["/species", "/classes", "/powers", "/monsters", "/sources"]) {
      expect(
        container.querySelector(`a[href="${path}"]`),
        `the about page should not be a dead end; it must offer ${path}`,
      ).not.toBeNull();
    }
  });

  it("puts About in the breadcrumb trail", () => {
    renderAbout();

    const crumbs = screen.getByRole("navigation", { name: /breadcrumb/i });
    expect(within(crumbs).getByText("About")).toBeInTheDocument();
  });
});
