/**
 * What this site is, and what it is not.
 *
 * This page exists because the two facts a returning reader needs cannot both
 * be said in a hero. The hero has room for "this picks up where sw5e.com left
 * off" and nothing more; it has no room for what carried over, what did not,
 * or the distinction between continuing somebody's work and speaking for them.
 * That last one is the reason this is a page rather than another sentence:
 * being the successor is not being official, the gap between the two is legally
 * load-bearing, and a claim that big should be stated somewhere it can be read
 * in full rather than compressed until it overclaims.
 *
 * It is also the page a search for "what happened to sw5e.com" can land on. A
 * reader whose bookmark went quiet does not search for this site by name —
 * they search for the one they lost. Nothing on the site answered that query
 * before, which is exactly how a continuation ends up looking like a rival.
 *
 * The counts come from the manifest rather than from prose. Every number in
 * here is one the build can check, for the same reason the meta description
 * stopped listing content types by hand: a page that describes the library has
 * to be regenerated by the library, or it becomes the most confidently wrong
 * page on the site.
 */

import { Link } from "react-router";

import { Breadcrumbs } from "~/components/site-chrome";
import { getManifest } from "~/content/dataset.server";
import { SOURCE_META, SOURCE_ORDER } from "~/content/source-meta";
import { TYPE_ORDER } from "~/content/type-meta";
import type { Route } from "./+types/about";

export function meta() {
  return [
    { title: "What this site is — Star Wars 5e" },
    {
      name: "description",
      content:
        "Star Wars 5e's reference lived at sw5e.com until its maintainer " +
        "stepped down. This site is the continuation: the same fan " +
        "conversion and the same books, maintained and searchable. " +
        "Unofficial, and not affiliated with Lucasfilm or Wizards of the Coast.",
    },
  ];
}

export async function loader() {
  const manifest = getManifest();
  return {
    total: manifest.types.reduce((sum, type) => sum + type.count, 0),
    counts: Object.fromEntries(
      manifest.types.map((type) => [type.id, type.count]),
    ) as Record<string, number>,
  };
}

export default function About({ loaderData }: Route.ComponentProps) {
  const { total, counts } = loaderData;

  // Rendered as a sentence fragment rather than a list, because the books are
  // the reassurance ("the same books") and not the subject of the page.
  const books = SOURCE_ORDER.map((code) => SOURCE_META[code].name);
  const bookList = `${books.slice(0, -1).join(", ")} and ${books.at(-1)}`;

  return (
    <div className="page">
      <Breadcrumbs trail={[{ label: "About" }]} />
      <div className="page-head">
        <p className="page-eyebrow">About</p>
        <h1>What this site is</h1>
        <p className="lede">
          The maintained continuation of the Star Wars 5e reference that lived
          at sw5e.com.
        </p>
      </div>

      <div className="prose-body">
        <p>
          Star Wars 5e is a fan conversion of fifth-edition Dungeons &amp;
          Dragons, made by Galiphile and a community of contributors. For years
          the reference for it lived at sw5e.com. The person maintaining that
          site stepped down, and it stopped being updated — which is an ordinary
          thing to happen to a project somebody ran for free, and no criticism
          of anyone. What it left behind was a rulebook nobody was tending.
        </p>
        <p>
          This site is where that work continues. It is the same conversion and
          the same books —{" "}
          {bookList} — rebuilt as a reference that is kept current:{" "}
          {total.toLocaleString("en-US")} entries across {TYPE_ORDER.length}{" "}
          categories, every one of them a real page at its own address, every
          one of them prerendered as plain HTML so it loads instantly, works
          without JavaScript and can be found by a search engine.
        </p>
        <p>
          If you arrived on a bookmark that stopped working, this is where it
          points now. Nothing was dropped on the way across, and a good deal was
          added: the {(counts.classes ?? 0).toLocaleString("en-US")} classes and
          their {(counts.archetypes ?? 0).toLocaleString("en-US")} archetypes,
          the whole of Starships of the Galaxy, the enhanced item catalogue, and
          the rules text itself.
        </p>

        <h2>What this site is not</h2>
        <p>
          It is not official, and the difference matters. Star Wars and
          everything in it belong to Lucasfilm. The conversion is community work
          made under Wizards of the Coast&rsquo;s Fan Content Policy. This site
          is unofficial fan content and is not affiliated with, endorsed by or
          sponsored by Lucasfilm or Wizards of the Coast.
        </p>
        <p>
          It also does not speak for sw5e.com or for the people who ran it. It
          carries their work forward, with thanks and with credit; it claims no
          authority they gave it and no standing they did not. Continuing
          something is not the same as being it.
        </p>

        <h2>Where to start</h2>
        <p>
          Press <kbd>/</kbd> anywhere on the site to search everything at once,
          or browse{" "}
          <Link to="/species">species</Link>,{" "}
          <Link to="/classes">classes</Link>,{" "}
          <Link to="/powers">powers</Link> or{" "}
          <Link to="/monsters">creature stat blocks</Link>. Every entry says
          which book it came from, and the{" "}
          <Link to="/sources">source books</Link> page collects them.
        </p>
      </div>
    </div>
  );
}
