/**
 * The page that carries the site's claim about itself.
 *
 * These assertions are unusually literal about wording, and that is deliberate.
 * The distinction between "this continues sw5e.com" and "this is sw5e.com" is
 * legally load-bearing — the first is a statement of stewardship, the second is
 * an impersonation and an implied endorsement the site has no right to claim.
 * A future edit tightening the prose could erase that distinction in one pass
 * without anybody noticing, so the disclaimers are pinned here rather than left
 * to review.
 */

import { render, screen, within } from "@testing-library/react";
import { createRoutesStub } from "react-router";
import { describe, expect, it } from "vitest";

import About from "./about";
import type { Route } from "./+types/about";

const loaderData = {
  total: 7191,
  counts: { classes: 10, archetypes: 137 },
};

function renderAbout(data: typeof loaderData = loaderData) {
  const Stub = createRoutesStub([
    {
      path: "/about",
      Component: () =>
        About({ loaderData: data } as unknown as Route.ComponentProps),
    },
  ]);
  return render(<Stub initialEntries={["/about"]} />);
}

describe("About route", () => {
  it("names the site it continues", () => {
    renderAbout();

    expect(screen.getAllByText(/sw5e\.com/i).length).toBeGreaterThan(0);
  });

  it("says plainly that the previous site stopped being updated, and why", () => {
    renderAbout();

    expect(
      screen.getByText(/stepped down/i),
      "a reader whose bookmark went quiet needs the reason, not a redirect",
    ).toBeInTheDocument();
  });

  it("tells a reader arriving on a dead bookmark that their entries are here", () => {
    renderAbout();

    expect(screen.getByText(/bookmark that stopped working/i)).toBeInTheDocument();
  });

  it("describes the corpus with numbers the build supplies", () => {
    renderAbout();

    // Every count on this page comes from the manifest. Prose that describes a
    // library and is not regenerated by it becomes the most confidently wrong
    // page on the site — which is exactly what happened to the old home page
    // meta description.
    expect(screen.getByText(/7,191 entries/)).toBeInTheDocument();
    expect(screen.getByText(/137 archetypes/)).toBeInTheDocument();
  });

  it("states that the site is unofficial and unaffiliated", () => {
    renderAbout();

    const disclaimer = screen.getByText(
      /not affiliated with, endorsed by or sponsored by Lucasfilm or Wizards of the Coast/i,
    );
    expect(disclaimer).toBeInTheDocument();
  });

  it("never claims to be the previous site or to speak for it", () => {
    const { container } = renderAbout();
    const text = container.textContent ?? "";

    // The claim the site is entitled to make is that it continues the work.
    // The claims it is not entitled to make are that it *is* that site, that it
    // is official, or that anyone handed it authority.
    expect(text).toMatch(/where that work continues/i);
    expect(text).toMatch(/does not speak for sw5e\.com/i);
    expect(text).not.toMatch(/\bthe official\b/i);
  });

  it("credits the conversion to the people who made it", () => {
    renderAbout();

    expect(screen.getByText(/Galiphile/)).toBeInTheDocument();
    expect(screen.getByText(/Fan Content Policy/)).toBeInTheDocument();
  });

  it("sends the reader on into the library", () => {
    const { container } = renderAbout();

    for (const path of ["/species", "/classes", "/powers", "/monsters", "/sources"]) {
      expect(
        container.querySelector(`a[href="${path}"]`),
        `the about page should not be a dead end; it must offer ${path}`,
      ).not.toBeNull();
    }
  });

  it("puts About in the breadcrumb trail", () => {
    renderAbout();

    const crumbs = screen.getByRole("navigation", { name: /breadcrumb/i });
    expect(within(crumbs).getByText("About")).toBeInTheDocument();
  });
});
